version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.fixed
    container_name: recycling-api
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./ml_model:/app/ml_model
    environment:
      - PYTHONPATH=/app
      - DEBUG=true
      - FIREBASE_CREDENTIALS_PATH=/app/firebase-credentials.json
    restart: unless-stopped